# -*- coding: utf-8 -*-

from odoo import models, fields, api, _

# Define selection values here to avoid duplication
JOB_CATEGORIES = [
    ('client_acquisition', 'Client Acquisition/Lead Generation'),
    ('positioning', 'Agency Positioning/Differentiation'),
    ('pricing_strategy', 'Pricing Strategy/Optimization'),
    ('team_efficiency', 'Team Efficiency/Workflows'),
    ('service_expansion', 'Service Expansion/Development'),
    ('client_retention', 'Client Retention/Satisfaction'),
    ('agency_scaling', 'Agency Scaling/Growth'),
    ('reporting_systems', 'Reporting/Analytics Systems'),
    ('other', 'Other'), # Added an 'Other' option
]

class JtbdJobPattern(models.Model):
    _name = 'jtbd.job.pattern'
    _description = 'JTBD Pattern'
    _order = 'sequence, name' # Added default order

    name = fields.Char(
        string='Pattern Name',
        required=True,
        help="A concise name for this JTBD pattern (e.g., 'Client Acquisition - Digital Marketing Agency')."
    )
    sequence = fields.Integer(default=10) # For ordering patterns
    active = fields.Boolean(default=True) # To easily activate/deactivate patterns

    job_category = fields.Selection(
        selection=JOB_CATEGORIES,
        string='Job Category',
        help="Select the primary job category this pattern relates to."
    )
    situation_template = fields.Text(
        string='Situation Template',
        help="Template text for the 'When...' part of the job statement."
    )
    motivation_template = fields.Text(
        string='Motivation Template',
        help="Template text for the 'I want to...' part of the job statement."
    )
    outcome_template = fields.Text(
        string='Outcome Template',
        help="Template text for the 'So I can...' part of the job statement."
    )
    # Renamed agency size fields for clarity based on Odoo 18 field names
    agency_size_min = fields.Integer(
        string='Min Agency Size',
        help="Minimum agency size (number of employees) this pattern typically applies to. 0 for no minimum."
    )
    agency_size_max = fields.Integer(
        string='Max Agency Size',
        help="Maximum agency size (number of employees) this pattern typically applies to. 0 for no maximum."
    )
    # Instead of linking directly to tools (which might not exist or change),
    # let's use tags or keywords for tech stack relevance.
    tech_stack_keywords = fields.Char(
        string='Related Tech Stack Keywords',
        help="Comma-separated keywords related to technology stacks (e.g., 'HubSpot, Salesforce, SEO Tools')."
    )
    # Added description/notes field
    notes = fields.Text(
        string='Notes',
        help="Internal notes or further details about this pattern."
    )

    jtbd_ai_personalization_suggestions = fields.Text(
        string="AI Personalization Angle Suggestions",
        readonly=True, # Populated by external process/AI
        copy=False,
        help="Placeholder: Suggestions generated by AI on how to personalize content/messaging for this specific job pattern (Populated via Phase 4+ Integration)."
    )

    # --- ADD Trace Link Counter and Action ---
    jtbd_trace_link_count = fields.Integer(
        compute='_compute_trace_link_count',
        string="# Trace Links"
    )

    def _compute_trace_link_count(self):
        """ Computes the number of trace links using search_count loop. """
        TraceLink = self.env['jtbd.trace.link']
        trace_link_model_id = self.env['ir.model']._get_id(self._name)
        if not trace_link_model_id:
            for record in self: record.jtbd_trace_link_count = 0
            return
        for record in self:
            try:
                count = TraceLink.search_count([ ('source_model_id', '=', trace_link_model_id), ('source_res_id', '=', record.id) ])
                record.jtbd_trace_link_count = count
            except Exception as e:
                 _logger.error(f"Error counting trace links for Outcome Map {record.id}: {e}", exc_info=True)
                 record.jtbd_trace_link_count = 0

    def action_open_trace_links(self):
        """ Opens a wizard to CREATE a new trace link for this Job Pattern. """
        self.ensure_one()
        source_model_id = self.env['ir.model']._get_id(self._name)
        return {
            'name': _('Create Trace Link for Job Pattern'),
            'type': 'ir.actions.act_window',
            'res_model': 'jtbd.create.trace.link.wizard', # Target the wizard
            'view_mode': 'form',
            'target': 'new',
            'context': {
                'default_source_model_id': source_model_id,
                'default_source_res_id': self.id,
                'default_name': f'Link for Pattern: {self.name[:30]}...'
            }
        }
    # --- END Trace Link Counter and Action ---